### ISSUE TITLE
Add E2E tests using Cypress.io

### ISSUE THREAD

**Issue by bahmutov** [swimlane/ngx-ui#114]
Hi everyone,

What do you plan to do for E2E testing? Can I propose using https://www.cypress.io/ that is going to be open sourced soon and thus is a good match for this open source project?

I took liberty of writing a few tests against https://swimlane.github.io/ngx-ui/ and you can see the tests in https://github.com/bahmutov/e2e-ngx-ui repo. 

![cypress-runner](https://user-images.githubusercontent.com/2212006/30725265-576a66e8-9f11-11e7-94ea-bc376a0d1789.png)

The testing tool itself is a dev dependency, works on Mac and CI (Windows is coming) and you can just keep it running as you work with the code. A typical test for a form for example looks a lot like Mocha/Jasmine unit test

https://github.com/bahmutov/e2e-ngx-ui/blob/df7ede09e8af8d2e402fa5fdf89d9540f134e295/cypress/integration/basic-spec.js#L6-L14

```js
  before(() => {
    cy.visit('/')
    cy.get('.page-loader')
      .should('not.be.visible', {timeout: 20000})
  })
  it("loads", () => {
    cy.contains("Angular Style and Component Library")
  })
```

There is huge number of commands and assertions included, plus the docs at https://docs.cypress.io are really good.

I setup CI on Circle, but any CI would work. We also have free dashboard for OSS projects which can store screenshots / test results / video recording of runs. For this project it is at https://dashboard.cypress.io/#/projects/psie99/runs

<img width="926" alt="e2e-runs" src="https://user-images.githubusercontent.com/2212006/30725308-d5532068-9f11-11e7-8cf9-45961365b136.png">

Videos of runs is really useful to debug failing CI tests

![e2e-video](https://user-images.githubusercontent.com/2212006/30725317-e6c9b082-9f11-11e7-8365-190ddd10cd9d.jpg)

Let me know if this is something the project needs. The tests could be part of the `swimlane/ngx-ui` repo or some separate repo like `swimlane/ngx-ui-e2e` for example, whatever makes sense for you. We at Cypress would be happy to promote our free (and soon OSS) tool by helping people start E2E testing.

**Comment by Hypercubed** [comment]
Hello Gleb,

Thank you for the information.  I am working on getting Cypress up an running across several of our projects (both open and internal), this obviously takes some time.  `ngx-ui-e2e` is very helpful and I will try to get it into ngx-ui ASAP.

**Comment by bahmutov** [comment]
@Hypercubed of course! and I will be very happy to answer any questions on https://gitter.im/cypress-io/cypress and the docs are a good resource: just search there, a good answer usually shows up :) https://docs.cypress.io
