### ISSUE TITLE
Hotkeys floating button not visible when --aot

### ISSUE THREAD

**Issue by ScottSpittle** [swimlane/ngx-ui#115]
If I build with --aot or server with --aot, the hotkeys floating button that sits in the bottom right of the screen does not get rendered. and the hotkeys no longer work

**Comment by ScottSpittle** [comment]
A work around is to register them manually instead of using annotations

**Comment by aacebo** [comment]
no longer a reproducible issue, built lib and started demo using --aot and hotkeys still functional.
