### ISSUE TITLE
Reactive forms ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by ihabZhaika** [swimlane/ngx-ui#116]
Hi,
i tried to use ngx-input with form builder

`
        <ngx-input
          type="text"
          [label]="'Name'"
          [autofocus]="true"
          formControlName="os"
          [hint]="'OS'"
        >
        </ngx-input>`
every thing works but in the console the following error is begin thrown
`InputComponent.html:2 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after `

with normal input there is no problem

**Comment by marjan-georgiev** [comment]
Can you provide a plunkr where this can be reproduced please?

**Comment by Hypercubed** [comment]
Close due to lack of input.
