### ISSUE TITLE
Range-slider

### ISSUE THREAD

**Issue by psy-man** [swimlane/ngx-ui#123]
Range slider is a typical component in every project, so it would be great if you add it.

![screen shot 2017-10-04 at 2 20 45 pm](https://user-images.githubusercontent.com/9465260/31173360-dad95dce-a90f-11e7-9756-3e9076766f43.png)

Thanks in advance!

**Comment by amcdnl** [comment]
We implemented the native slider, it does not have support for range sliders (yet).
