### ISSUE TITLE
Drawer Translation Safari bug

### ISSUE THREAD

**Issue by tkumpanenko** [swimlane/ngx-ui#131]
Hi, I found small bug with drawer. On safari 11.00
<img width="1440" alt="image 2017-10-23 at 10 24 21" src="https://user-images.githubusercontent.com/7837024/31876767-8dc10308-b7dc-11e7-9e0b-6e30b3ab2d6d.png">

**Comment by Hypercubed** [comment]
Please reopen if you still have this issue, I cannot reproduce.
