### ISSUE TITLE
[Angular 5] Bug: Update flex-layout to 2.0.0-beta.10

### ISSUE THREAD

**Issue by guillaumegarcia13** [swimlane/ngx-ui#132]
Hi,
Could you please update f@angular/flex-layout dependency to 2.0.0-beta.10
The old Renderer (instead of the new Rendered2) within @angular/flex-layout seems to break ngx-ui when upgrading to Angular 5.
![image](https://user-images.githubusercontent.com/2786038/32321850-d8bcb904-bfc2-11e7-9ae7-e25ba5ef740b.png)

Thanks!

**Comment by RicardoVaranda** [comment]
This is also creating inconsistency in npm installs:

![image](https://user-images.githubusercontent.com/6951312/32367950-f7149bba-c07b-11e7-95b1-5ae32995d959.png)

**Comment by marjan-georgiev** [comment]
flex-layout@2.0.0-beta.10 also causes peer dependency issues. They released beta.11, but it not reachable through npm yet, see this issue: https://github.com/angular/flex-layout/issues/489

**Comment by marjan-georgiev** [comment]
This should be fixed in 19.0.1
