### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-ui#138]
It would be great to add a Rich Text Editor to the list - for basic text functions like:

Bold, Italic, Super/SubScript, Underline, Special Symbols, Href tagging

**Comment by bostondevin** [comment]
I guess that's what Froala is for!

**Comment by Hypercubed** [comment]
I've been investigating this somewhat.  The issues is that most decent rich text editors are not good code editors... and code editors are not rich text editors.  So which rich text editor you use will depend on your needs.  Try ngx-quill...
