### ISSUE TITLE
ngx-section standard classes...

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-ui#139]
In the Bootstrap library, on the panel component (which would map to the ngx-section component in your library) there are classNames that change the background color of the panel heading the same way buttons can be styled and themed:  

panel-success
panel-info
panel-warning
panel-danger
etc...

Since your buttons have this, it would be great if the panels worked the same - keeping consistent with the bootstrap stuff.

**Comment by Hypercubed** [comment]
Yes, we are planning to do a full style refresh across the board.
