### ISSUE TITLE
bug: ngx-ui does not work with angular-cli

### ISSUE THREAD

**Issue by BernhardRode** [swimlane/ngx-ui#15]
node: v7.5.0
@angular/cli: 1.0.0-beta.30

just tried a 'ng new demo-app' and added ngx-ui ... 

```
cd demo-app
npm i @swimlane/ngx-ui --S
```

as soon, as i add 

```
import { NgxUIModule } from '@swimlane/ngx-ui';
```

to app.module.ts, the the cli outputs an 

```
error ERROR in /developer/src/demo/src/app/app.module.ts (8,29): 
Cannot find module '@swimlane/ngx-ui'.)
```

**Comment by amcdnl** [comment]
Ya, its cuz the AoT build isn't working right. :(

**Comment by BernhardRode** [comment]
The file "release/index.d.ts" is missing in the release.

**Comment by beeman** [comment]
@amcdnl when I'm running without aot it tends to give the same error:

```
ng serve --aot false
```

**Comment by AlexanderKozhevin** [comment]
Well, it works fine. 
I copied SCSS files from library to my project. And cloned assets as also. 
And install typescript2.4.2 in project.

**Comment by FengData** [comment]
how to import it in my angular-cli project

**Comment by ScottSpittle** [comment]
@FengData 
npm install --save @swimlane/ngx-ui

then in the module you wish to use the ngx-ui components simply add NgxUIModule to your modules imports array

**Comment by Hypercubed** [comment]
Here is demo Angular CLI app using ngx-ui and other @swimlane libs.  If you are still having issues using ngx-ui in angular cli please reopen.
