### ISSUE TITLE
Notification icons are not shown.

### ISSUE THREAD

**Issue by vugar005** [swimlane/ngx-ui#161]
Hi 
When using notification component its icons are not showing.Seems like missing icons.
here is how notification looks like:
https://image.ibb.co/b40BVn/icon_Issue.png
When inspecting html of notification I notice
after `<span class = "icon icon-check-filled ng-star-inserted"> </span`> , _:before is missing._
Am I missing something?
Angular version:  5.2
ngx-ui version:  20 (also tried v19)
Thanks in advance

**Comment by marjan-georgiev** [comment]
I am not able to reproduce. Can you try creating a stackblitz or a github repo and reproduce that?

Are you importing loading `@swimlane/ngx-ui/release/index.css`

**Comment by vugar005** [comment]
@marjan-georgiev 
Thanks it works. But the problem is this new theme overwrites my other styles such as buttons and tables. How can I solve this in a clean way?

**Comment by marjan-georgiev** [comment]
ngx-ui is a complete UI library and meant to be used as a whole. I assume you only want to use it for some things, but not others? You could possibly do that by importing individual styles from https://github.com/swimlane/ngx-ui/tree/master/release/styles and https://github.com/swimlane/ngx-ui/tree/master/release/assets,
but that can get complicated to set up.

Another way is to have your own style overrides.

**Comment by vugar005** [comment]
I see. @marjan-georgiev .
Yes I am using ngx-ui for only some components. I also use angular material and bootstrap 4. Fromt my point of view, ngx-ui should not add custom styles to elements. It should only only if directive applied to it.

**Comment by marjan-georgiev** [comment]
What about trying to only import the icons font? https://github.com/swimlane/ngx-ui/blob/master/release/styles/fonts/index.scss

If you're not using other parts of ngx-ui, see if that might fix your original icons issue.

**Comment by vugar005** [comment]
@marjan-georgiev  . I tried to add @import '~@swimlane/ngx-ui/release/styles/fonts/index.scss' to styles.scss but it now complains 

> Lessons-app\node_modules\assets\fonts\source-sans\SourceSansPro-SemiboldItalic.ttf doesn't exist
Can I solve this ? Thanks

**Comment by marjan-georgiev** [comment]
Try adding this to your webpack config:
```
      new webpack.LoaderOptionsPlugin({
        options: {
          context: root(),
          sassLoader: {
            includePaths: [
              root('node_modules', '@swimlane/ngx-ui', 'release'),
              root('node_modules', '@swimlane/ngx-ui', 'release', 'styles'),
            ]
          },
          postcss: function() {
            return [ autoprefixer ];
          }
        }
      })
```

It tells the webpack sass loader where to look for the styles and fonts.

**Comment by vugar005** [comment]
@marjan-georgiev . Thanks so much for your help. Even though I think it is not a good idea to modify webpack, seems it is only choice.

**Comment by marjan-georgiev** [comment]
I agree, but since you're importing raw scss files, webpack needs to know how to compile them.

**Comment by vugar005** [comment]
@marjan-georgiev  
Without webpack config tried to solve it with custom icon. You have provided api for notification create:
```
notificationService.create({
    title: 'Patch Failed!',
    icon: 'exclamation-circle',
    rateLimit: false,
    timeout: false
  })
```
Here I use font awesome icon (exclamation-circle) . But again notification service does not show icon.
Do you have idea how to solve this? 
Thanks in advance!

**Comment by marjan-georgiev** [comment]
That will not work because it must be a ngx-ui icon.

However, you can choose to have your own custom template. Take a look at `Templated Notifications` in the demo:

https://swimlane.github.io/ngx-ui/#notification

You can define the whole template of the notification in there.

**Comment by vugar005** [comment]
@marjan-georgiev 
yes it is also a good idea. Thanks a lot.
