### ISSUE TITLE
Namespace ''@swimlane/dragula'' has no exported member 'DragulaOptions'

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-ui#180]
Getting this issue - using the latest Angular version (6.0.2)

ERROR in node_modules/@swimlane/ngx-dnd/release/services/drake-store.service.d.ts(21,35): error TS2694: Namespace ''@swimlane/dragula'' has no exported member 'DragulaOptions'

**Comment by marjan-georgiev** [comment]
Did you mean to open this in ngx-dnd? ngx-ui does not have ngx-dnd as a dependency.
