### ISSUE TITLE
deep-linking

### ISSUE THREAD

**Issue by tycho01** [swimlane/ngx-ui#20]
Would it be possible to enable deep-linking on the demo site, e.g. to ensure the menu links give distinct URLs? This would help for sharing, saving links to different parts, as well as to see which links lead to distinct pages.
On a related note, currently clicking on items in the colors category takes me to the page while I'd expect it to also scroll to the appropriate section. After this, I assumed this was the case for other categories as well, and hence skipped over `icons` not realizing it did have its own distinct section.

**Comment by marjan-georgiev** [comment]
Yes, that's on the roadmap, but not a high priority at the moment.

If you would be willing to contribute, pull requests are most welcome.
