### ISSUE TITLE
Getting error about moment with latest

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-ui#202]
ERROR in node_modules/@swimlane/ngx-ui/release/components/calendar/calendar.component.d.ts(3,8): error TS1192: Module '"/Users/bostondevin/websites/ace/node_modules/moment/moment"' has no default export.
node_modules/@swimlane/ngx-ui/release/components/date-time/date-time.component.d.ts(3,8): error TS1192: Module '"/Users/bostondevin/websites/ace/node_modules/moment/moment"' has no default export.

**Comment by marjan-georgiev** [comment]
`moment` has been moved to peerDependencies as of 21.7.0. You would need to add it to your own list of dependencies:

`npm i moment --s`

**Comment by bostondevin** [comment]
Just tried it and still getting the same error - happens on three different machines

**Comment by metalex9** [comment]
@bostondevin Which version of TypeScript are you using?

**Comment by metalex9** [comment]
@bostondevin In the meantime, I have rolled back the `@latest` tagged version on npm to 21.4.4; go ahead and run `npm i @swimlane/ngx-ui@latest` to install the previous version of ngx-ui. Sorry for the trouble!

**Comment by bostondevin** [comment]
I'm on 2.9.2 - I thought that was the latest one we could use with the CLI, but I could be out of date!

**Comment by metalex9** [comment]
https://momentjs.com/docs/#/use-it/typescript/

Looks like you need to have `"allowSyntheticDefaultImports": true` in `compilerOptions` of your TypeScript configuration. If you're still trying to use 21.7.0, give that a try. We'll update the project readme before we re-release the next version.
