### ISSUE TITLE
Unexpected value 'undefined' imported by the module 'NgxUIModule

### ISSUE THREAD

**Issue by bbougot** [swimlane/ngx-ui#207]
Got this error while using this module in an Angular 7 project. Used to worked perfectly with 21.7.0 version (all peerDependencies and module are correctly installed and declared).

**Comment by heyepe** [comment]
Experiencing the same issue on v22.0.2

**Comment by ivoglent** [comment]
Any news for this issue? I like this module but can not use :(

**Comment by ivoglent** [comment]
figured out by myself.
Run ng serve with option : --aot false
Example : 
```
ng --configuration=dev serve --aot false
```
For moment export error. try add :
```
"allowSyntheticDefaultImports" : true,
```
to compilerOptions of tsconfig.json.

**Comment by bbougot** [comment]
Problem is I need AOT for production release.

**Comment by marjan-georgiev** [comment]
This should be fixed in 25.0.0

**Comment by Anhbta** [comment]
Still having same issue in 25.6.3, don't know how to fix the build.

**Comment by FBNjsilvamarques** [comment]
Having same issue too. It's not possible to build with aot. Version 25.6.2

**Comment by cmckni3** [comment]
Having this issue on 25.6.3 and 25.7.0.

**Comment by cmckni3** [comment]
Works great in 25.8.0
