### ISSUE TITLE
Getting error about moment-timezone with latest

### ISSUE THREAD

**Issue by bostondevin** [swimlane/ngx-ui#218]
Getting this anything version 24.0.0+

ERROR in node_modules/@swimlane/ngx-ui/lib/components/calendar/calendar.component.d.ts(3,20): error TS2307: Cannot find module 'moment-timezone'.
node_modules/@swimlane/ngx-ui/lib/components/date-time/date-time.component.d.ts(3,20): error TS2307: Cannot find module 'moment-timezone'.
node_modules/@swimlane/ngx-ui/lib/pipes/timezone.pipe.d.ts(2,25): error TS2307: Cannot find module 'moment-timezone'.

**Comment by Hypercubed** [comment]
Hello... Moment-timezone is now a peer.  You will need to install it yourself since npm does not install peers for you.
