### ISSUE TITLE
Bug: Select items are not reloaded on change

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-ui#22]
Current behavior: If I remove an option from the list of options after selecting it, it is still visible and I am able to select it again, which throws an error.

Expected behavior: If I remove an option from the list of options, it should disappear from the dropdown.

Note, I am defining the options declaratively:
```
 <ngx-select-option *ngFor="let role of roles" [name]="role.name" [value]="role.id"></ngx-select-option>
```

![image](https://cloud.githubusercontent.com/assets/8687/22973943/462695ec-f380-11e6-9184-1684d389679c.png)

**Comment by amcdnl** [comment]
Use the options input until https://github.com/angular/angular/issues/13248 is fixed.

**Comment by aacebo** [comment]
@marjan-georgiev is this still an issue or was it fixed with the on-push/async change we made earlier this month requested by @Hypercubed ?

**Comment by marjan-georgiev** [comment]
This is fixed. Closing.
