### ISSUE TITLE
minor: npm says latest ist 25.1.1 but github release list says its 25.0.0

### ISSUE THREAD

**Issue by wunderkind2k1** [swimlane/ngx-ui#225]
The sources at https://github.com/swimlane/ngx-ui/releases  says the newest version is 25.0.0
but a 

> yarn version @swimlane/ngx-ui gives

`<snip
    author:
   { name:
      'Swimlane' },
  version:
   '25.1.0',
</snip>`

with a hash of
`shasum:
      '1e6869890dcbcb220c610c289d3c93cd2c5926a2',`

Pls create a release at github to make clear what the latest version is.

**Comment by marjan-georgiev** [comment]
The latest tag has been pushed, thanks for pointing that out.
