### ISSUE TITLE
Add gradient button class

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-ui#233]
Add a `btn-primary-gradient` class to the list of button classes that looks like the button on the right here:

![image](https://user-images.githubusercontent.com/8687/52816830-6b078180-30a2-11e9-82ea-eacffdd5ea9c.png)

Update the buttons page in the demo to showcase it

**Comment by haeminn** [comment]
@marjan-georgiev 
"button on the right" as in any button class that has background color?
