### ISSUE TITLE
Add [hidden] input to ngx-select-option.

### ISSUE THREAD

**Issue by Hypercubed** [swimlane/ngx-ui#238]
The `ngx-select` component uses the `ngx-select-option` children directives to populate the drop-down options.  We provide an input to disable certain options but those options still show in the drop-down list.  I'd suggest adding a `[hidden]` input to `ngx-select-option` that hides an option (cannot be selected or seen in the dropdown) but still makes it available for display if the option is selected in the value.

**Comment by haeminn** [comment]
Will this attribute be added to `ngx-select-option` directive or `ngx-select`? Regardless of what the value of 'disabled' is, if 'hidden', then it should hide that option?

**Comment by Hypercubed** [comment]
Correct... disable make a selection unselectable... but still visible. `hidden` should hide the selection but leave it selectable.

Also... let's make sure `[hidden]` doesn't conflict with any existing ng directives.
