### ISSUE TITLE
[slider] Don't allow sliders to run into/pass each other

### ISSUE THREAD

**Issue by cmckni3** [swimlane/ngx-ui#277]
This happens with `multiple=true`.

**Comment by KingDarBoja** [comment]
Can you provide more info about this issue? Is it related to the two-sliders (the ones with min and max values)?

**Comment by cmckni3** [comment]
Sure, let me attach a gif example.

**Comment by cmckni3** [comment]
Ohhh I see the values are adjusted. I think it's weird UX. I can live with it though.

![2019-05-18_13-17-21 (1)](https://user-images.githubusercontent.com/735717/57973521-a3538000-796f-11e9-98ea-d9ec788d858e.gif)

code:

```
<ngx-slider [(ngModel)]="tagSlider"
                     [multiple]="true" [step]="1"
                     [filled]="true"
                     [min]="1"
                     [max]="100"
                     (change)="handleSliderUpdate()"></ngx-slider>
```

**Comment by cmckni3** [comment]
Feel free to close this/I can close this.
