### ISSUE TITLE
Can't use component modules individually

### ISSUE THREAD

**Issue by cmckni3** [swimlane/ngx-ui#278]
```
ERROR in : Unexpected value 'SliderModule in [REDACTED]/node_modules/@swimlane/ngx-ui/swimlane-ngx-ui.d.ts' imported by the module 'SubmissionsModule in [REDACTED]'. Please add a @NgModule annotation.
```

Trying to import `SliderComponent` directly gives a similar error but says to use `@Pipe/@Component/@Directive` annotation.

Maybe related https://github.com/ng-packagr/ng-packagr/issues/482

**Comment by cmckni3** [comment]
I did a lot of digging and testing. For some reason this happens due to the extra `export { SliderModule as øe } ...` when exporting `NgxUIModule`.

**Comment by KingDarBoja** [comment]
@cmckni3 You are right, in order to use modules individually you must import them using the alias name provided at the package definition.

@marjan-georgiev Can I remove the alias on a PR so we don't have to deal with this? Also provide some basic documentation for this would help (either markdown or some DocSPA as in ngx-graph).

**Comment by marjan-georgiev** [comment]
Where are you guys seeing that alias?

**Comment by marjan-georgiev** [comment]
Oh, in `swimlane-ngx-ui.d.ts`. @KingDarBoja yeah, if you know a way to prevent those, please send a PR.

**Comment by cmckni3** [comment]
@KingDarBoja yes but the alias doesn’t resolve correctly hence the error.

Seems like a problem with @angular/compiler but I know the material team provides this functionality.

My ng-packagr projects only use a single module so I would have to investigate when I have a chance.

**Comment by KingDarBoja** [comment]
@cmckni3 Did this got solved in a recent release?
