### ISSUE TITLE
Tree view : not getting styles or buttons

### ISSUE THREAD

**Issue by MM3y3r** [swimlane/ngx-ui#295]
Any idea why i am not getting the expand buttons? I am using all your deps and angular 8 beta.

https://swimlane.github.io/ngx-ui/tree

Trying to replicate tree view. How do i get the icons in there?

![image](https://user-images.githubusercontent.com/4068962/60919898-2e2d6880-a297-11e9-9a77-b62e1c468e3c.png)

**Comment by marjan-georgiev** [comment]
Looks like you need to override the icon colors too. Try inspect element, they should be there.

**Comment by marjan-georgiev** [comment]
Also, did you include the ngx-ui styles?

```
"stylePreprocessorOptions": {
              "includePaths": [
                "./node_modules/@swimlane/ngx-ui/lib/styles",
                "./node_modules/@swimlane/ngx-ui/lib/assets"
              ]
            }
```
