### ISSUE TITLE
Coerce inputs

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-ui#321]
Our input components do not convert the inputs into the expected value types (i.e. boolean, integer)
This issue is present in both our inputs, as well as the json-editor component.

Should use @angular/cdk/coercion package

Reference:
https://netbasal.com/trust-but-verify-coerce-your-component-inputs-bdb743e8b579

**Comment by aacebo** [comment]
we are incrementally fixing this issue with feature branches, soon to be finished.
