### ISSUE TITLE
Cannot find module 'moment-timezone'

### ISSUE THREAD

**Issue by KingDarBoja** [swimlane/ngx-ui#333]
Hello Swimlane Team,

I updated the `@swimlane/ngx-ui` package from `22.0.1` to `27.1.0` and got this error message while trying to serve my app:

```bash
ERROR in ../node_modules/@swimlane/ngx-ui/lib/components/calendar/calendar.component.d.ts:3:20 - error TS2307: Cannot find module 'moment-timezone'.

3 import moment from 'moment-timezone';
                     ~~~~~~~~~~~~~~~~~
../node_modules/@swimlane/ngx-ui/lib/components/date-time/date-time.component.d.ts:3:20 - error TS2307: Cannot find module 'moment-timezone'.

3 import moment from 'moment-timezone';
                     ~~~~~~~~~~~~~~~~~
../node_modules/@swimlane/ngx-ui/lib/pipes/timezone.pipe.d.ts:2:25 - error TS2307: Cannot find module 'moment-timezone'.

2 import * as moment from 'moment-timezone';
```

Sample [repo](https://github.com/KingDarBoja/CRUD-Angular6).

Cheers!

**Comment by Hypercubed** [comment]
Hello, `moment-timezone` is a peer dependency and will need ti be installed desperately.

**Comment by KingDarBoja** [comment]
> Hello, `moment-timezone` is a peer dependency and will need ti be installed desperately.

Why don't make it part of the package as dependency?  Just saying...

**Comment by Hypercubed** [comment]
I'll need to look into it... `moment` is also a peer at the moment.
