### ISSUE TITLE
.ngx-tabs: uppercase style is being applied to all buttons instead of just tab buttons

### ISSUE THREAD

**Issue by hankconn** [swimlane/ngx-ui#371]
The styling for ".ngx-dialog.wizard .ngx-dialog-content .ngx-tabs .ngx-tab button" includes a "text-transform:uppercase;". This is intended for the tab buttons (the buttons at the top which allow you to switch tabs). However, this styling is being applied to ALL buttons inside the .ngx-tab. I think to fix this the .ngx-tabs-list class needs to be specified in the CSS styling to restrict it to only the actual tab buttons.

**Comment by marjan-georgiev** [comment]
Merged the PR. Will be in next release.
