### ISSUE TITLE
Confirm dialog should allow customizing button text, styling, or placing.

### ISSUE THREAD

**Issue by luisb90** [swimlane/ngx-ui#486]
Confirm dialog should allow user to customize the styling and text of the buttons for the confirm alert dialog, as well as their placement (cancel on left or right)

**Comment by Hypercubed** [comment]
@luisb90 I put this in a few weeks ago... https://github.com/swimlane/ngx-ui/pull/472. you need more than that?

**Comment by marjan-georgiev** [comment]
I think we need to also be able to change the text on the confirm button.
