### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by RicardoVaranda** [swimlane/ngx-ui#53]
Hey guys,

Would it be possible to provide us with a guide on how to theme the UI / components, I've been looking around but couldn't seem to find any.

Thanks for the great set of components! 👍

**Comment by amcdnl** [comment]
Its on the roadmap!

**Comment by RicardoVaranda** [comment]
Thanks for the update 🐼  looking forward to it :)

**Comment by kroeder** [comment]
Any update on this? Currently, I got no chance to edit styles unless I set every css property !important but this causes a couple of unwanted side effects

I could overide the ngx-ui properties without using !important if I could import the compiled .css file of ngx-ui after mine in e.g. angular-cli.json but I saw it is shipped within your index.ts

Any ideas for a workaround?

**Comment by Hypercubed** [comment]
It's in our plans... but a ways off.  Closing thsi for now.
