### ISSUE TITLE
Password eye icon should change based on password visibility

### ISSUE THREAD

**Issue by Hypercubed** [swimlane/ngx-ui#657]
The current password show/hide implementation doesn't indicate it's state.
![image](https://user-images.githubusercontent.com/509946/132377323-96da295b-b02f-45cd-8dc1-0bf2dc45a3ab.png)

![image](https://user-images.githubusercontent.com/509946/132377342-293d025b-8daa-4782-9ee7-d9bc38365d27.png)

Password eye icon should change based on password visibility:

Prior art:  
![image](https://user-images.githubusercontent.com/509946/132376472-dd93ddcd-b7e5-49a2-92eb-532d6a967b0d.png)

![image](https://user-images.githubusercontent.com/509946/132378064-40f5ba9c-972b-4f1d-9bd0-f95076b61744.png)

**Comment by JoelLau** [comment]
hi @Hypercubed , can I take this on as part of Hacktoberfest?

**Comment by Hypercubed** [comment]
Hi @JoelLau , we welcome outside contributions.   Please be aware that it often takes us a long time to review outside changes.  Please don't be discouraged by that!

**Comment by JoelLau** [comment]
no worries! I have a few questions regarding the icon though:

1. Is there an existing I can (with the eye closed) I can use?
    - If so, should I access it via conditional class(.e.g. icon-eye-closed) or via a CSS selector that overrides the contents of .icon-eye::before?

**Comment by Hypercubed** [comment]
Checkout the icons page (https://swimlane.github.io/ngx-ui/icons) there is a `ngx-eye-disabled`.
