### ISSUE TITLE
Active tabs in ngx-tabs should be more visible.

### ISSUE THREAD

**Issue by Hypercubed** [swimlane/ngx-ui#659]
Currently there is no color change for the active tab's label:

![image](https://user-images.githubusercontent.com/509946/132544613-aa3f9ff1-34f3-4fe7-88cb-beb03ffaa38b.png)

The active tab label color should be white.  Example:

![image](https://user-images.githubusercontent.com/509946/132544664-db75bbef-198a-437c-b5bd-96c855423038.png)

**Comment by mcwenger** [comment]
@Hypercubed The initial (non-active) tab's color is incorrect as well, per our designs. It should be `$color-blue-grey-250`. Should we adjust this issue or create a new one?

**Comment by Hypercubed** [comment]
If you can update this one that would be great.
