### ISSUE TITLE
Error on fresh angular install

### ISSUE THREAD

**Issue by mkubdev** [swimlane/ngx-ui#670]
Hi, awesome work. Love the design of theses components.
But i can't add it to my app.

- Created a freshly angular 12 project
- Use `npm i @swimlane/ngx-ui --S`

And got :
![Capture](https://user-images.githubusercontent.com/50140834/134700262-165222f9-6b9d-41b3-be33-8bc6f19fccd2.JPG)

Am i doing something wrong ?

**Comment by Hypercubed** [comment]
For now please add `--legacy-peer-deps`

**Comment by mkubdev** [comment]
Thanks @Hypercubed !
