### ISSUE TITLE
Can't install ngx-ui

### ISSUE THREAD

**Issue by IttiwatNir** [swimlane/ngx-ui#73]
When I use command npm i @swimlane/ngx-ui --S ,
It has error like this 

npm ERR! path F:\workspace\ERPWorkspace\erpweb\node_modules\@angular\flex-layout
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'F:\workspace\ERPWorkspace\erpweb\node_modules\@angular\flex-layout' -> 'F:\workspace\ERPWorkspace\erpweb\node_modules\@angular\.flex-layout.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ittiwat123\AppData\Roaming\npm-cache\_logs\2017-06-26T06_08_38_918Z-debug.log

- angular/cli: 1.1.3
- node: 8.1.2
- npm: 5.0.3
- os: win32 x64
- angular/animations: 4.2.4
- angular/common: 4.2.4
- angular/compiler: 4.2.4
- angular/core: 4.2.4
- angular/forms: 4.2.4
- angular/http: 4.2.4
- angular/platform-browser: 4.2.4
- angular/platform-browser-dynamic: 4.2.4
- angular/router: 4.2.4
- angular/compiler-cli: 4.2.4
- angular/language-service: 4.2.4

**Comment by RicardoVaranda** [comment]
Hey @IttiwatNir seems like an issue with flex-layout that is causing this issue, could you please do the following within your project directory:

```
rm -rf node_modules
npm cache clean
npm i @swimlane/ngx-ui --S
```
