### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-ui#9]

**Comment by Hypercubed** [comment]
How is this different from the current `Day` theme?

**Comment by amcdnl** [comment]
Its the same.

**Comment by Hypercubed** [comment]
Closing.

**Comment by amcdnl** [comment]
This is not completed, Day mode is toggleable but not fully implemented.

**Comment by Hypercubed** [comment]
Got it, to clarify for future reference, light theme referenced here refers to theming of components not the demo page.
