### ISSUE TITLE
n ambient enum declarations member initializer must be constant expression

### ISSUE THREAD

**Issue by AlexanderKozhevin** [swimlane/ngx-ui#95]
I tried to use it with Angular CLI without AOT stuff.
But I'm getting a bunch of typescript errors. 
Can anybody provide me with some guidance on how to fix that?

```
ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/input/input-types.d.ts (2,12): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/input/input-types.d.ts (3,14): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/input/input-types.d.ts (4,16): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/input/input-types.d.ts (5,16): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/date-time/date-time.type.d.ts (2,12): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/date-time/date-time.type.d.ts (3,12): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/date-time/date-time.type.d.ts (4,16): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/notification/notification-style.type.d.ts (2,12): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/notification/notification-style.type.d.ts (3,15): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/notification/notification-style.type.d.ts (4,13): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/notification/notification-style.type.d.ts (5,15): In ambient enum declarations member initializer must be constant expression.

ERROR in /Users/alexanderkozhevin/Desktop/hypermedia/pheromone/node_modules/@swimlane/ngx-ui/release/components/notification/notification-style.type.d.ts (6,12): In ambient enum declarations member initializer must be constant expression.
```

**Comment by AlexanderKozhevin** [comment]
Hmm, I guess caching problem. Got fixed after I reloaded and restarted everything.

**Comment by AlexanderKozhevin** [comment]
Hah. Nope. That's weird.
So when I comment it out, compile, and then uncomment again. It works. 
But it keeps giving me those errors.

**Comment by BenRacicot** [comment]
I can second this issue. `In ambient enum declarations member initializer must be constant expression.` Has anyone got to the bottom of it?

**Comment by mkoczorowski** [comment]
no.. but +1

**Comment by penniath** [comment]
+1

**Comment by amcdnl** [comment]
You need typescript 2.4

**Comment by AlexanderKozhevin** [comment]
@amcdnl I got 
* typescript 2.42.
* ng-cli 1.3.0-rc.5

Still the same error.

**Comment by AlexanderKozhevin** [comment]
I installed latest typescript version inside project. Not globally. 
```
npm install typescript@next --save
```
And it's working now

**Comment by wilkinsleung0712** [comment]
npm install typescript@2.4.2--save has saved my day

**Comment by adarshaj** [comment]
Can't upgrade due to another error in rxjs : https://github.com/ReactiveX/rxjs/issues/2539

What's a reasonable workaround for this?

**Comment by adrian-moisa** [comment]
Also the release candidate instead of the nightly build can be used. `npm install typescript@rc --save`

**Comment by cwalcott** [comment]
According to [this comment](https://github.com/angular/angular/issues/19287#issuecomment-331250655) Angular isn't compatible with TypeScript 2.4 or 2.5 yet.

**Comment by ogix** [comment]
Please reopen this issue because as @cwalcott mentioned we cannot update TS to 2.4 version now

**Comment by AlexanderKozhevin** [comment]
@ogix What does it mean?
Which TS. global or for this specific project?

**Comment by ogix** [comment]
Local, since this version will be used when bundling using Angular CLI. I get a warning that 2.4 ant later TS is not supported yet and it can cause problems.

**Comment by bhushangahire** [comment]
Any solution on this other than updating to 2.4?

**Comment by JerryBels** [comment]
Same problem

**Comment by bischofb** [comment]
I was stoked to try out this grid because ag-grid is crazy bloated and this looks it has just enough features without the bloat. But I get this error as well with a clean Linux build and fresh install of Angular CLI. Why would an angular grid be built for a version of TS that isn't compatible with Angular? I'll look for another lightweight grid and maybe revisit this one again in the future. :-(

**Comment by t-palmer** [comment]
I am looking at the Angular Changelog here:
https://github.com/angular/angular/blob/master/CHANGELOG.md

Angular 4.3.4 was made available August 10, 2017 and it supports Typescript 2.4.

You probably want to upgrade now to Typescript 2.4. According to the Changelog, Angular 5 requires it.

**Comment by hmendezm** [comment]
Thanks, wilkinsleung0712. you save me time.

**Comment by ridj87** [comment]
Im having this issue and tried to update ts to 2.4.2.
here is my setup.
@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.11-b01c2d7
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.3
typescript: 2.4.2
webpack: 3.8.1


Still getting the errors

**Comment by gurwinder-macrew** [comment]
> npm install [typescript@2.4.2--save](mailto:typescript@2.4.2--save) has saved my day

worked for me
